# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the 'recommended' set of lints from `package:flutter_lints`.
# Uncomment individual rules below to customize how the linter checks
# this codebase.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # avoid_print: false
    # prefer_single_quotes: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
